[35mapp/admin/(protected)/customers/[id]/addresses/[addressId]/edit/page.tsx[m
[35mapp/admin/(protected)/customers/[id]/addresses/new/page.tsx[m
[35mapp/admin/(protected)/customers/[id]/contacts/[contactId]/edit/page.tsx[m
[35mapp/admin/(protected)/customers/[id]/contacts/new/page.tsx[m
[35mapp/admin/(protected)/customers/[id]/edit/page.tsx[m
[35mapp/admin/(protected)/customers/[id]/not-found.tsx[m
[35mapp/admin/(protected)/customers/[id]/page.tsx[m
[35mapp/admin/(protected)/customers/error.tsx[m
[35mapp/admin/(protected)/customers/loading.tsx[m
[35mapp/admin/(protected)/customers/new/page.tsx[m
[35mapp/admin/(protected)/customers/page.tsx[m
[35mapp/admin/(protected)/goods-receipts/new/page.tsx[m
[35mapp/admin/(protected)/goods-receipts/page.tsx[m
[35mapp/admin/(protected)/page.tsx[m
[35mapp/admin/(protected)/purchase-orders/[id]/page.tsx[m
[35mapp/admin/(protected)/purchase-orders/page.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/items/page.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/page.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/quotations/[quotationId]/page.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/quotations/new/page.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/quotations/page.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/suppliers/loading.tsx[m
[35mapp/admin/(protected)/rfqs/[id]/suppliers/page.tsx[m
[35mapp/admin/(protected)/rfqs/loading.tsx[m
[35mapp/admin/(protected)/rfqs/new/page.tsx[m
[35mapp/admin/(protected)/rfqs/page.tsx[m
[35mcomponents/admin/AdminHeader.tsx[m
[35mcomponents/admin/AdminSidebar.tsx[m
[35mcomponents/admin/customers/CustomerFilters.tsx[m
[35mcomponents/admin/customers/CustomerForm.tsx[m
[35mcomponents/admin/customers/CustomerPagination.tsx[m
[35mcomponents/admin/customers/CustomerStatusActions.tsx[m
[35mcomponents/admin/customers/CustomerSummaryCards.tsx[m
[35mcomponents/admin/customers/CustomerTable.tsx[m
[35mcomponents/admin/customers/addresses/CustomerAddressForm.tsx[m
[35mcomponents/admin/customers/addresses/CustomerAddressesSection.tsx[m
[35mcomponents/admin/customers/contacts/CustomerContactForm.tsx[m
[35mcomponents/admin/customers/contacts/CustomerContactsSection.tsx[m
[35mcomponents/admin/purchase-orders/detail/purchase-order-reference.tsx[m
[35mcomponents/admin/purchase-orders/purchase-order-table.tsx[m
[35mcomponents/admin/rfqs/create-rfq-wizard.tsx[m
[35mcomponents/admin/rfqs/detail/rfq-summary-cards.tsx[m
[35mcomponents/admin/rfqs/items/rfq-items-step.tsx[m
[35mcomponents/admin/rfqs/quotation/quotation-form.tsx[m
[35mcomponents/admin/rfqs/quotation/quotation-header.tsx[m
[35mcomponents/admin/rfqs/review/rfq-review-step.tsx[m
[35mcomponents/admin/rfqs/rfq-row-actions.tsx[m
[35mcomponents/admin/rfqs/rfq-status-badge.tsx[m
[35mcomponents/admin/rfqs/rfq-table.tsx[m
[35mcomponents/admin/rfqs/rfq-workspace-tabs.tsx[m
[35mcomponents/admin/rfqs/suppliers/rfq-suppliers-step.tsx[m
