/*
 * =========================================================
 * 128 — Supplier Return Credit Applications
 *
 * PART A — Foundation
 *
 * PURPOSE
 * -------
 *
 * Creates the immutable application ledger used when credit
 * generated by a posted Supplier Return is applied against a
 * later Quick Purchase obligation for the same supplier.
 *
 *
 * ACCOUNTING MODEL
 * ----------------
 *
 * Supplier Return posting may create:
 *
 *   Dr Supplier Advances
 *       Cr Inventory / VAT
 *
 * That Supplier Advances balance represents money/value owed
 * back to us by the supplier.
 *
 * When the credit is later applied against another payable:
 *
 *   Dr Accounts Payable
 *       Cr Supplier Advances
 *
 *
 * IMPORTANT
 * ---------
 *
 * This table records APPLICATION history.
 *
 * It does NOT rewrite:
 *
 *   - historical supplier payments
 *   - original Quick Purchase payment allocations
 *   - original Supplier Return GL journal
 *
 * Supplier Return credit usage remains separately auditable.
 * =========================================================
 */


/* =========================================================
 * 1. Supplier Return Credit Applications
 * ========================================================= */

create table if not exists
  public.supplier_return_credit_applications
(
  id uuid
    primary key
    default gen_random_uuid(),

  supplier_return_id uuid
    not null
    references public.supplier_returns(id)
    on delete restrict,

  quick_purchase_id uuid
    not null
    references public.quick_purchases(id)
    on delete restrict,

  supplier_id uuid
    not null
    references public.suppliers(id)
    on delete restrict,

  application_date date
    not null
    default current_date,

  posting_date date
    not null
    default current_date,

  currency_code text
    not null,

  exchange_rate numeric(18, 8)
    not null
    default 1,

  amount numeric(18, 2)
    not null,

  base_amount numeric(18, 2)
    not null,

  journal_entry_id uuid
    references public.gl_journal_entries(id)
    on delete restrict,

  notes text,

  created_by uuid
    references auth.users(id)
    on delete restrict,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint supplier_return_credit_applications_amount_check
    check (
      amount > 0
    ),

  constraint supplier_return_credit_applications_base_amount_check
    check (
      base_amount > 0
    ),

  constraint supplier_return_credit_applications_exchange_rate_check
    check (
      exchange_rate > 0
    ),

  constraint supplier_return_credit_applications_currency_check
    check (
      currency_code ~ '^[A-Z]{3}$'
    ),

  /*
   * One application record must never point the Supplier
   * Return back to its own originating Quick Purchase.
   *
   * The controlled application function will additionally
   * validate this using supplier_returns.quick_purchase_id.
   */
  constraint supplier_return_credit_application_unique
    unique (
      supplier_return_id,
      quick_purchase_id,
      id
    )
);


/* =========================================================
 * 2. Indexes
 * ========================================================= */

create index if not exists
  supplier_return_credit_applications_return_idx
on
  public.supplier_return_credit_applications(
    supplier_return_id
  );


create index if not exists
  supplier_return_credit_applications_purchase_idx
on
  public.supplier_return_credit_applications(
    quick_purchase_id
  );


create index if not exists
  supplier_return_credit_applications_supplier_idx
on
  public.supplier_return_credit_applications(
    supplier_id
  );


create index if not exists
  supplier_return_credit_applications_posting_date_idx
on
  public.supplier_return_credit_applications(
    posting_date
  );


create unique index if not exists
  supplier_return_credit_applications_journal_unique
on
  public.supplier_return_credit_applications(
    journal_entry_id
  )
where
  journal_entry_id is not null;


/* =========================================================
 * 3. Row Level Security
 * ========================================================= */

alter table
  public.supplier_return_credit_applications
enable row level security;


drop policy if exists
  "Management can view supplier return credit applications"
on
  public.supplier_return_credit_applications;


create policy
  "Management can view supplier return credit applications"

on
  public.supplier_return_credit_applications

for select

to authenticated

using (
  public.is_admin()
);


/* =========================================================
 * 4. Direct Write Protection
 *
 * Application records must be created only through the
 * controlled SECURITY DEFINER workflow that will follow.
 * ========================================================= */

revoke insert,
       update,
       delete
on
  public.supplier_return_credit_applications
from authenticated;


/* =========================================================
 * 5. Documentation
 * ========================================================= */

comment on table
  public.supplier_return_credit_applications
is
  'Immutable audit ledger recording application of posted Supplier Return credits against later Quick Purchase supplier obligations.';


comment on column
  public.supplier_return_credit_applications.supplier_return_id
is
  'Posted Supplier Return providing the supplier credit.';


comment on column
  public.supplier_return_credit_applications.quick_purchase_id
is
  'Quick Purchase obligation against which the Supplier Return credit is applied.';


comment on column
  public.supplier_return_credit_applications.amount
is
  'Supplier Return credit amount applied in document currency.';


comment on column
  public.supplier_return_credit_applications.base_amount
is
  'Applied Supplier Return credit translated to AED base currency.';


comment on column
  public.supplier_return_credit_applications.journal_entry_id
is
  'Posted General Ledger journal reclassifying Supplier Advances into Accounts Payable reduction.';

/* =========================================================
 * 6. Apply Supplier Return Credit
 *
 * PURPOSE
 * -------
 *
 * Applies available credit from one posted Supplier Return
 * against an outstanding Quick Purchase belonging to the
 * same supplier.
 *
 *
 * ACCOUNTING
 * ----------
 *
 *   Dr Accounts Payable
 *       Cr Supplier Advances
 *
 *
 * CONTROL
 * -------
 *
 * The Supplier Return and target Quick Purchase are locked
 * before availability is calculated.
 *
 * This prevents concurrent applications from consuming the
 * same supplier credit or payable twice.
 * ========================================================= */

create or replace function
  public.apply_supplier_return_credit(
    p_supplier_return_id uuid,
    p_quick_purchase_id uuid,
    p_amount numeric,
    p_application_date date
      default current_date,
    p_posting_date date
      default current_date,
    p_notes text
      default null
  )
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;

  v_return
    public.supplier_returns%rowtype;

  v_purchase
    public.quick_purchases%rowtype;

  v_available_credit numeric(18, 2);

  v_outstanding_payable numeric(18, 2);

  v_amount numeric(18, 2);

  v_base_amount numeric(18, 2);

  v_accounts_payable_account_id uuid;

  v_supplier_advances_account_id uuid;

  v_application_id uuid;

  v_journal_id uuid;

  v_lines jsonb;

begin

  /* =======================================================
   * Authentication
   * ======================================================= */

  v_user_id :=
    auth.uid();


  if
    v_user_id is null
  then
    raise exception
      'Authentication is required.';
  end if;


  if
    not public.is_admin()
  then
    raise exception
      'Administrator access is required.';
  end if;


  /* =======================================================
   * Validate Input
   * ======================================================= */

  if
    p_supplier_return_id is null
  then
    raise exception
      'Supplier Return ID is required.';
  end if;


  if
    p_quick_purchase_id is null
  then
    raise exception
      'Quick Purchase ID is required.';
  end if;


  if
    p_amount is null
    or
    p_amount <= 0
  then
    raise exception
      'Supplier credit application amount must be greater than zero.';
  end if;


  if
    p_application_date is null
  then
    raise exception
      'Application date is required.';
  end if;


  if
    p_posting_date is null
  then
    raise exception
      'Posting date is required.';
  end if;


  v_amount :=
    round(
      p_amount,
      2
    );


  /* =======================================================
   * Lock Supplier Return
   * ======================================================= */

  select
    *
  into
    v_return
  from
    public.supplier_returns
  where
    id =
      p_supplier_return_id
  for update;


  if not found then
    raise exception
      'Supplier Return was not found.';
  end if;


  if
    v_return.status <>
      'posted'
  then
    raise exception
      'Supplier Return % must be posted before its credit can be applied.',
      v_return.return_number;
  end if;


  if
    coalesce(
      v_return.supplier_credit_amount,
      0
    ) <= 0
  then
    raise exception
      'Supplier Return % does not contain available supplier credit.',
      v_return.return_number;
  end if;


  /* =======================================================
   * Prevent Application to Original Purchase
   * ======================================================= */

  if
    v_return.quick_purchase_id =
      p_quick_purchase_id
  then
    raise exception
      'Supplier Return credit cannot be applied back to its originating Quick Purchase.';
  end if;


  /* =======================================================
   * Calculate Available Supplier Credit
   * ======================================================= */

  v_available_credit :=
    round(
      coalesce(
        v_return.supplier_credit_amount,
        0
      )
      -
      coalesce(
        v_return.supplier_credit_applied_amount,
        0
      ),
      2
    );


  if
    v_available_credit <= 0
  then
    raise exception
      'Supplier Return % has no remaining supplier credit.',
      v_return.return_number;
  end if;


  if
    v_amount >
      v_available_credit
  then
    raise exception
      'Requested amount % exceeds available Supplier Return credit %.',
      v_amount,
      v_available_credit;
  end if;


  /* =======================================================
   * Lock Target Quick Purchase
   * ======================================================= */

  select
    *
  into
    v_purchase
  from
    public.quick_purchases
  where
    id =
      p_quick_purchase_id
  for update;


  if not found then
    raise exception
      'Target Quick Purchase was not found.';
  end if;


  /* =======================================================
   * Supplier Validation
   * ======================================================= */

  if
    v_purchase.supplier_id is null
  then
    raise exception
      'Quick Purchase % does not have a registered supplier.',
      v_purchase.purchase_number;
  end if;


  if
    v_purchase.supplier_id <>
      v_return.supplier_id
  then
    raise exception
      'Supplier Return % and Quick Purchase % belong to different suppliers.',
      v_return.return_number,
      v_purchase.purchase_number;
  end if;


  /* =======================================================
   * Currency Validation
   *
   * Cross-currency Supplier Return applications require a
   * separate FX realization model and are intentionally not
   * permitted here.
   * ======================================================= */

  if
    upper(
      trim(
        v_purchase.currency_code
      )
    )
    <>
    upper(
      trim(
        v_return.currency_code
      )
    )
  then
    raise exception
      'Supplier Return credit currency % does not match Quick Purchase currency %.',
      v_return.currency_code,
      v_purchase.currency_code;
  end if;


  /* =======================================================
   * Refresh Operational Payable
   *
   * Existing Quick Purchase synchronization remains the
   * authority for operational paid/balance fields.
   * ======================================================= */

  perform
    public.sync_quick_purchase_paid_amount(
      v_purchase.id
    );


  /*
   * Reload after synchronization while retaining the row
   * lock in this transaction.
   */

  select
    *
  into
    v_purchase
  from
    public.quick_purchases
  where
    id =
      p_quick_purchase_id
  for update;


  /* =======================================================
   * Calculate Outstanding Payable
   * ======================================================= */

  v_outstanding_payable :=
  round(
    greatest(
      coalesce(
        v_purchase.balance_due,
        0
      ),
      0
    ),
    2
  );

  if
    v_outstanding_payable <= 0
  then
    raise exception
      'Quick Purchase % does not have an outstanding payable.',
      v_purchase.purchase_number;
  end if;


  if
    v_amount >
      v_outstanding_payable
  then
    raise exception
      'Requested amount % exceeds Quick Purchase outstanding payable %.',
      v_amount,
      v_outstanding_payable;
  end if;


  /* =======================================================
   * Resolve GL Accounts
   * ======================================================= */

  v_accounts_payable_account_id :=
    public.get_mapped_gl_account(
      'accounts_payable'
    );


  v_supplier_advances_account_id :=
    public.get_mapped_gl_account(
      'supplier_advances'
    );


  if
    v_accounts_payable_account_id is null
  then
    raise exception
      'Accounts Payable GL account mapping is missing.';
  end if;


  if
    v_supplier_advances_account_id is null
  then
    raise exception
      'Supplier Advances GL account mapping is missing.';
  end if;


  /* =======================================================
   * Base Currency Amount
   * ======================================================= */

  v_base_amount :=
    round(
      v_amount
      *
      v_return.exchange_rate,
      2
    );


  if
    v_base_amount <= 0
  then
    raise exception
      'Supplier credit base amount must be greater than zero.';
  end if;


  /* =======================================================
   * Create Immutable Application Record
   * ======================================================= */

  insert into
    public.supplier_return_credit_applications
    (
      supplier_return_id,
      quick_purchase_id,
      supplier_id,

      application_date,
      posting_date,

      currency_code,
      exchange_rate,

      amount,
      base_amount,

      notes,

      created_by,
      created_at,
      updated_at
    )

  values
    (
      v_return.id,
      v_purchase.id,
      v_return.supplier_id,

      p_application_date,
      p_posting_date,

      upper(
        trim(
          v_return.currency_code
        )
      ),

      v_return.exchange_rate,

      v_amount,
      v_base_amount,

      nullif(
        trim(
          coalesce(
            p_notes,
            ''
          )
        ),
        ''
      ),

      v_user_id,
      now(),
      now()
    )

  returning
    id
  into
    v_application_id;


  /* =======================================================
   * Build GL Lines
   *
   * Dr Accounts Payable
   * Cr Supplier Advances
   * ======================================================= */

  v_lines :=
    jsonb_build_array(

      jsonb_build_object(
        'glAccountId',
          v_accounts_payable_account_id,

        'debit',
          v_amount,

        'credit',
          0,

        'baseDebit',
          v_base_amount,

        'baseCredit',
          0,

        'description',
          'Supplier credit applied to '
          ||
          v_purchase.purchase_number,

        'supplierId',
          v_return.supplier_id
      ),

      jsonb_build_object(
        'glAccountId',
          v_supplier_advances_account_id,

        'debit',
          0,

        'credit',
          v_amount,

        'baseDebit',
          0,

        'baseCredit',
          v_base_amount,

        'description',
          'Supplier Return credit applied from '
          ||
          v_return.return_number,

        'supplierId',
          v_return.supplier_id
      )

    );


  /* =======================================================
   * Post Through Controlled GL Engine
   * ======================================================= */

  v_journal_id :=
    public.post_erp_gl_journal(
      'supplier_return_credit_application',

      v_application_id,

      v_return.return_number
      ||
      ' -> '
      ||
      v_purchase.purchase_number,

      p_application_date,

      p_posting_date,

      'Supplier Return credit application - '
      ||
      v_return.return_number
      ||
      ' against '
      ||
      v_purchase.purchase_number,

      upper(
        trim(
          v_return.currency_code
        )
      ),

      v_return.exchange_rate,

      v_lines
    );


  /* =======================================================
   * Finalize Application
   * ======================================================= */

  update
    public.supplier_return_credit_applications

  set
    journal_entry_id =
      v_journal_id,

    updated_at =
      now()

  where
    id =
      v_application_id;


  /* =======================================================
   * Consume Supplier Return Credit
   * ======================================================= */

  update
    public.supplier_returns

  set
    supplier_credit_applied_amount =
      round(
        coalesce(
          supplier_credit_applied_amount,
          0
        )
        +
        v_amount,
        2
      ),

    updated_by =
      v_user_id,

    updated_at =
      now()

  where
    id =
      v_return.id;


  /* =======================================================
   * Synchronize Target Quick Purchase
   * ======================================================= */

  perform
    public.sync_quick_purchase_paid_amount(
      v_purchase.id
    );


  return
    v_application_id;

end;
$$;


/* =========================================================
 * 7. Permissions
 * ========================================================= */

revoke all
on function
  public.apply_supplier_return_credit(
    uuid,
    uuid,
    numeric,
    date,
    date,
    text
  )
from public;


grant execute
on function
  public.apply_supplier_return_credit(
    uuid,
    uuid,
    numeric,
    date,
    date,
    text
  )
to authenticated;


/* =========================================================
 * 8. Documentation
 * ========================================================= */

comment on function
  public.apply_supplier_return_credit(
    uuid,
    uuid,
    numeric,
    date,
    date,
    text
  )
is
  'Atomically applies available credit from a posted Supplier Return against an outstanding Quick Purchase for the same supplier and currency. Posts Dr Accounts Payable / Cr Supplier Advances through the controlled General Ledger engine.';

/* =========================================================
 * 9. Synchronize Quick Purchase Payable
 *
 * Extends Migration 127.
 *
 * paid_amount remains historical payment activity only:
 *
 *   payment_opening_amount
 *   +
 *   posted Supplier Payment allocations
 *
 *
 * adjusted purchase liability:
 *
 *   original Quick Purchase total
 *   -
 *   posted Supplier Returns originating from this purchase
 *   -
 *   Supplier Return credits applied TO this purchase
 *
 *
 * Supplier Return credit applications therefore settle AP
 * without pretending that additional cash was paid.
 * ========================================================= */

create or replace function
  public.sync_quick_purchase_paid_amount(
    p_quick_purchase_id uuid
  )
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_grand_total
    numeric(18, 2);

  v_opening_amount
    numeric(18, 2);

  v_allocated_amount
    numeric(18, 2);

  v_supplier_return_amount
    numeric(18, 2);

  v_supplier_return_credit_applied
    numeric(18, 2);

  v_adjusted_purchase_total
    numeric(18, 2);

  v_paid_amount
    numeric(18, 2);

  v_balance_due
    numeric(18, 2);

  v_payment_status
    text;

begin

  /* -------------------------------------------------------
   * Lock Quick Purchase
   * ------------------------------------------------------- */

  select
    grand_total,
    payment_opening_amount

  into
    v_grand_total,
    v_opening_amount

  from
    public.quick_purchases

  where
    id =
      p_quick_purchase_id

  for update;


  if not found then
    raise exception
      'Quick Purchase was not found.';
  end if;


  /* -------------------------------------------------------
   * Historical Posted Supplier Payment Allocations
   * ------------------------------------------------------- */

  select
    coalesce(
      sum(
        allocation.amount
      ),
      0
    )

  into
    v_allocated_amount

  from
    public.supplier_payment_allocations
      allocation

  join
    public.supplier_payments
      payment

    on
      payment.id =
        allocation.supplier_payment_id

  where
    allocation.quick_purchase_id =
      p_quick_purchase_id

    and

    payment.status =
      'posted';


  /* -------------------------------------------------------
   * Posted Supplier Returns Originating From This Purchase
   * ------------------------------------------------------- */

  select
    coalesce(
      sum(
        supplier_return.grand_total
      ),
      0
    )

  into
    v_supplier_return_amount

  from
    public.supplier_returns
      supplier_return

  where
    supplier_return.quick_purchase_id =
      p_quick_purchase_id

    and

    supplier_return.status =
      'posted';


  /* -------------------------------------------------------
   * Supplier Return Credits Applied TO This Purchase
   * ------------------------------------------------------- */

  select
    coalesce(
      sum(
        application.amount
      ),
      0
    )

  into
    v_supplier_return_credit_applied

  from
    public.supplier_return_credit_applications
      application

  where
    application.quick_purchase_id =
      p_quick_purchase_id

    and

    application.journal_entry_id
      is not null;


  /* -------------------------------------------------------
   * Historical Amount Actually Paid
   *
   * Supplier Return credit applications deliberately do NOT
   * increase this figure.
   * ------------------------------------------------------- */

  v_paid_amount :=
    round(
      coalesce(
        v_opening_amount,
        0
      )
      +
      coalesce(
        v_allocated_amount,
        0
      ),
      2
    );


  if
    v_paid_amount >
      v_grand_total
      +
      0.01
  then
    raise exception
      'Quick Purchase payment exceeds the original purchase total.';
  end if;


  /* -------------------------------------------------------
   * Net Purchase Liability
   * ------------------------------------------------------- */

  v_adjusted_purchase_total :=
    greatest(
      round(
        v_grand_total
        -
        coalesce(
          v_supplier_return_amount,
          0
        )
        -
        coalesce(
          v_supplier_return_credit_applied,
          0
        ),
        2
      ),
      0
    );


  /* -------------------------------------------------------
   * Remaining AP
   * ------------------------------------------------------- */

  v_balance_due :=
    greatest(
      round(
        v_adjusted_purchase_total
        -
        v_paid_amount,
        2
      ),
      0
    );


  /* -------------------------------------------------------
   * Payment Status
   *
   * Preserve Migration 127 semantics.
   * ------------------------------------------------------- */

  if
  v_balance_due <=
    0
then

  v_payment_status :=
    'paid';


elsif
  v_paid_amount <=
    0
then

  v_payment_status :=
    'unpaid';

  elsif
    v_paid_amount <
      v_adjusted_purchase_total
  then

    v_payment_status :=
      'partially_paid';


  else

    v_payment_status :=
      'paid';

  end if;


  /* -------------------------------------------------------
   * Synchronize Quick Purchase
   * ------------------------------------------------------- */

  update
    public.quick_purchases

  set
    paid_amount =
      v_paid_amount,

    balance_due =
      v_balance_due,

    payment_status =
      v_payment_status

  where
    id =
      p_quick_purchase_id;

end;
$$;


/* =========================================================
 * 10. Documentation — Extended Payable Synchronization
 * ========================================================= */

comment on function
  public.sync_quick_purchase_paid_amount(
    uuid
  )
is
  'Synchronizes Quick Purchase payable state while preserving paid_amount as historical cash/payment activity. Outstanding liability is reduced by posted Supplier Returns and posted Supplier Return credit applications.';