/*
 * =========================================================
 * 129 — Supplier Return Credit Refunds
 *
 * PART A — Refund Foundation
 *
 * PURPOSE
 * -------
 *
 * Records money received back from a supplier against credit
 * generated by a posted Supplier Return.
 *
 *
 * ACCOUNTING MODEL
 * ----------------
 *
 * Supplier Return posting may create:
 *
 *   Dr Supplier Advances
 *       Cr Inventory / VAT
 *
 * That Supplier Advances balance can subsequently be:
 *
 *   A) applied against another supplier payable
 *
 *      Dr Accounts Payable
 *          Cr Supplier Advances
 *
 *   B) refunded by the supplier
 *
 *      Dr Bank / Cash
 *          Cr Supplier Advances
 *
 *
 * IMPORTANT
 * ---------
 *
 * Refunds are recorded independently from Supplier Return
 * credit applications.
 *
 * This preserves a complete audit trail showing whether
 * Supplier Return credit was:
 *
 *   - applied against another purchase
 *   - refunded through a financial account
 *   - still outstanding
 *
 * Direct writes are intentionally blocked. Refund records
 * will be created only through the controlled workflow added
 * later in this migration.
 * =========================================================
 */


/* =========================================================
 * 1. Supplier Return Credit Refunds
 * ========================================================= */

create table if not exists
  public.supplier_return_credit_refunds
(
  id uuid
    primary key
    default gen_random_uuid(),

  refund_number text
    not null,

  supplier_return_id uuid
    not null
    references public.supplier_returns(id)
    on delete restrict,

  supplier_id uuid
    not null
    references public.suppliers(id)
    on delete restrict,

  financial_account_id uuid
    not null
    references public.financial_accounts(id)
    on delete restrict,

  refund_date date
    not null
    default current_date,

  posting_date date
    not null
    default current_date,

  currency_code text
    not null,

  exchange_rate numeric(18, 8)
    not null
    default 1,

  amount numeric(18, 2)
    not null,

  base_amount numeric(18, 2)
    not null,

  account_transaction_id uuid
    references public.account_transactions(id)
    on delete restrict,

  journal_entry_id uuid
    references public.gl_journal_entries(id)
    on delete restrict,

  reference_number text,

  notes text,

  created_by uuid
    references auth.users(id)
    on delete restrict,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint supplier_return_credit_refunds_number_unique
    unique (
      refund_number
    ),

  constraint supplier_return_credit_refunds_amount_check
    check (
      amount > 0
    ),

  constraint supplier_return_credit_refunds_base_amount_check
    check (
      base_amount > 0
    ),

  constraint supplier_return_credit_refunds_exchange_rate_check
    check (
      exchange_rate > 0
    ),

  constraint supplier_return_credit_refunds_currency_check
    check (
      currency_code ~ '^[A-Z]{3}$'
    )
);


/* =========================================================
 * 2. Indexes
 * ========================================================= */

create index if not exists
  supplier_return_credit_refunds_return_idx
on
  public.supplier_return_credit_refunds(
    supplier_return_id
  );


create index if not exists
  supplier_return_credit_refunds_supplier_idx
on
  public.supplier_return_credit_refunds(
    supplier_id
  );


create index if not exists
  supplier_return_credit_refunds_financial_account_idx
on
  public.supplier_return_credit_refunds(
    financial_account_id
  );


create index if not exists
  supplier_return_credit_refunds_posting_date_idx
on
  public.supplier_return_credit_refunds(
    posting_date
  );


create unique index if not exists
  supplier_return_credit_refunds_account_transaction_unique
on
  public.supplier_return_credit_refunds(
    account_transaction_id
  )
where
  account_transaction_id is not null;


create unique index if not exists
  supplier_return_credit_refunds_journal_unique
on
  public.supplier_return_credit_refunds(
    journal_entry_id
  )
where
  journal_entry_id is not null;


/* =========================================================
 * 3. Row Level Security
 * ========================================================= */

alter table
  public.supplier_return_credit_refunds
enable row level security;


drop policy if exists
  "Management can view supplier return credit refunds"
on
  public.supplier_return_credit_refunds;


create policy
  "Management can view supplier return credit refunds"

on
  public.supplier_return_credit_refunds

for select

to authenticated

using (
  public.is_admin()
);


/* =========================================================
 * 4. Direct Write Protection
 *
 * Refunds must be created only through the controlled
 * SECURITY DEFINER workflow.
 * ========================================================= */

revoke insert,
       update,
       delete
on
  public.supplier_return_credit_refunds
from authenticated;


/* =========================================================
 * 5. Documentation
 * ========================================================= */

comment on table
  public.supplier_return_credit_refunds
is
  'Immutable audit ledger recording cash or bank refunds received against credit generated by posted Supplier Returns.';


comment on column
  public.supplier_return_credit_refunds.refund_number
is
  'Human-readable Supplier Return credit refund reference.';


comment on column
  public.supplier_return_credit_refunds.supplier_return_id
is
  'Posted Supplier Return whose available supplier credit is being refunded.';


comment on column
  public.supplier_return_credit_refunds.supplier_id
is
  'Supplier returning the money.';


comment on column
  public.supplier_return_credit_refunds.financial_account_id
is
  'Operational cash or bank financial account receiving the supplier refund.';


comment on column
  public.supplier_return_credit_refunds.amount
is
  'Supplier refund amount in document currency.';


comment on column
  public.supplier_return_credit_refunds.base_amount
is
  'Supplier refund amount translated into AED base currency.';


comment on column
  public.supplier_return_credit_refunds.account_transaction_id
is
  'Posted operational financial-account transaction representing money received from the supplier.';


comment on column
  public.supplier_return_credit_refunds.journal_entry_id
is
  'Posted General Ledger journal recording Dr Financial Account / Cr Supplier Advances.';


comment on column
  public.supplier_return_credit_refunds.reference_number
is
  'Optional external supplier, bank, transfer, cheque, or other refund reference.';

/* =========================================================
 * 6. Supplier Return Credit Refund Number Sequence
 * ========================================================= */

create sequence if not exists
  public.supplier_return_credit_refund_number_seq

start with 1
increment by 1
minvalue 1
no maxvalue
cache 1;


/* =========================================================
 * 7. Supplier Return Credit Refund Number Generator
 * ========================================================= */

create or replace function
  public.next_supplier_return_credit_refund_number(
    p_refund_date date
      default current_date
  )
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_number bigint;

begin

  v_number :=
    nextval(
      'public.supplier_return_credit_refund_number_seq'
    );


  return
    'SPRF-'
    ||
    extract(
      year
      from
      coalesce(
        p_refund_date,
        current_date
      )
    )::integer
    ||
    '-'
    ||
    lpad(
      v_number::text,
      6,
      '0'
    );

end;
$$;


/* =========================================================
 * 8. Refund Supplier Return Credit
 *
 * ACCOUNTING
 * ----------
 *
 *   Dr Financial Account
 *       Cr Supplier Advances
 *
 * OPERATIONAL TREASURY
 * --------------------
 *
 * Money IN is posted through:
 *
 *   public.post_account_transaction(...)
 *
 * CREDIT CONTROL
 * --------------
 *
 * Available Supplier Return credit is calculated as:
 *
 *   supplier_credit_amount
 *   -
 *   supplier_credit_applied_amount
 *   -
 *   posted refund amount
 *
 * The Supplier Return row is locked before this value is
 * calculated so concurrent refund/application attempts cannot
 * consume the same credit.
 * ========================================================= */

create or replace function
  public.refund_supplier_return_credit(
    p_supplier_return_id uuid,
    p_financial_account_id uuid,
    p_amount numeric,
    p_refund_date date
      default current_date,
    p_posting_date date
      default current_date,
    p_reference_number text
      default null,
    p_notes text
      default null
  )
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;

  v_return
    public.supplier_returns%rowtype;

  v_financial_account
    public.financial_accounts%rowtype;

  v_refund_id uuid;
  v_refund_number text;

  v_amount
    numeric(18, 2);

  v_base_amount
    numeric(18, 2);

  v_refunded_amount
    numeric(18, 2);

  v_available_credit
    numeric(18, 2);

  v_account_transaction_id uuid;
  v_journal_entry_id uuid;

  v_financial_gl_account_id uuid;
  v_supplier_advance_account_id uuid;

  v_lines jsonb;

begin

  /* =======================================================
   * Authentication
   * ======================================================= */

  v_user_id :=
    auth.uid();


  if
    v_user_id is null
  then
    raise exception
      'Authentication is required.';
  end if;


  if
    not public.is_admin()
  then
    raise exception
      'Administrator access is required.';
  end if;


  /* =======================================================
   * Inputs
   * ======================================================= */

  if
    p_supplier_return_id is null
  then
    raise exception
      'Supplier Return ID is required.';
  end if;


  if
    p_financial_account_id is null
  then
    raise exception
      'Financial account is required.';
  end if;


  v_amount :=
    round(
      coalesce(
        p_amount,
        0
      ),
      2
    );


  if
    v_amount <= 0
  then
    raise exception
      'Refund amount must be greater than zero.';
  end if;


  /* =======================================================
   * Lock Supplier Return
   * ======================================================= */

  select
    *
  into
    v_return

  from
    public.supplier_returns

  where
    id =
      p_supplier_return_id

  for update;


  if not found then
    raise exception
      'Supplier Return was not found.';
  end if;


  if
    v_return.status <>
      'posted'
  then
    raise exception
      'Supplier Return % must be posted before credit can be refunded.',
      v_return.return_number;
  end if;


  if
    v_return.supplier_id is null
  then
    raise exception
      'Supplier Return % does not have a registered supplier.',
      v_return.return_number;
  end if;


  if
    coalesce(
      v_return.supplier_credit_amount,
      0
    ) <= 0
  then
    raise exception
      'Supplier Return % does not have supplier credit available for refund.',
      v_return.return_number;
  end if;


  /* =======================================================
   * Existing Refund Consumption
   * ======================================================= */

  select
    coalesce(
      sum(
        refund.amount
      ),
      0
    )

  into
    v_refunded_amount

  from
    public.supplier_return_credit_refunds
      refund

  where
    refund.supplier_return_id =
      v_return.id

    and

    refund.journal_entry_id
      is not null;


  /* =======================================================
   * Remaining Credit
   * ======================================================= */

  v_available_credit :=
    greatest(
      round(
        coalesce(
          v_return.supplier_credit_amount,
          0
        )
        -
        coalesce(
          v_return.supplier_credit_applied_amount,
          0
        )
        -
        coalesce(
          v_refunded_amount,
          0
        ),
        2
      ),
      0
    );


  if
    v_available_credit <= 0
  then
    raise exception
      'Supplier Return % does not have remaining supplier credit.',
      v_return.return_number;
  end if;


    if
    v_amount >
      v_available_credit
  then
    raise exception
      'Refund amount % exceeds available Supplier Return credit % for %.',
      v_amount,
      v_available_credit,
      v_return.return_number;
  end if;


  /* =======================================================
   * Lock + Validate Financial Account
   * ======================================================= */

  select
    *
  into
    v_financial_account

  from
    public.financial_accounts

  where
    id =
      p_financial_account_id

  for update;


  if not found then
    raise exception
      'Financial account was not found.';
  end if;


  if
    not v_financial_account.is_active
  then
    raise exception
      'Financial account % is inactive.',
      v_financial_account.account_name;
  end if;


  if
    upper(
      v_financial_account.currency_code
    ) <>
    upper(
      v_return.currency_code
    )
  then
    raise exception
      'Financial account currency % does not match Supplier Return currency %.',
      v_financial_account.currency_code,
      v_return.currency_code;
  end if;


  if
    coalesce(
      v_return.exchange_rate,
      0
    ) <= 0
  then
    raise exception
      'Supplier Return % does not have a valid exchange rate.',
      v_return.return_number;
  end if;


  /* =======================================================
   * Base Currency
   * ======================================================= */

  v_base_amount :=
    round(
      v_amount
      *
      v_return.exchange_rate,
      2
    );


  if
    v_base_amount <= 0
  then
    raise exception
      'Refund base amount must be greater than zero.';
  end if;


  /* =======================================================
   * Create Refund Ledger Record
   * ======================================================= */

  v_refund_number :=
    public.next_supplier_return_credit_refund_number(
      coalesce(
        p_refund_date,
        current_date
      )
    );


  insert into
    public.supplier_return_credit_refunds
  (
    refund_number,
    supplier_return_id,
    supplier_id,
    financial_account_id,
    refund_date,
    posting_date,
    currency_code,
    exchange_rate,
    amount,
    base_amount,
    reference_number,
    notes,
    created_by
  )
  values
  (
    v_refund_number,
    v_return.id,
    v_return.supplier_id,
    v_financial_account.id,
    coalesce(
      p_refund_date,
      current_date
    ),
    coalesce(
      p_posting_date,
      current_date
    ),
    upper(
      v_return.currency_code
    ),
    v_return.exchange_rate,
    v_amount,
    v_base_amount,
    nullif(
      trim(
        coalesce(
          p_reference_number,
          ''
        )
      ),
      ''
    ),
    nullif(
      trim(
        coalesce(
          p_notes,
          ''
        )
      ),
      ''
    ),
    v_user_id
  )
  returning
    id
  into
    v_refund_id;


  /* =======================================================
   * Operational Financial Account — Money IN
   * ======================================================= */

  v_account_transaction_id :=
    public.post_account_transaction(
      v_financial_account.id,

      coalesce(
        p_refund_date,
        current_date
      ),

      'in',

      'other_in',

      v_amount,

      upper(
        v_return.currency_code
      ),

      v_return.exchange_rate,

      'supplier_return_credit_refund',

      v_refund_id,

      v_refund_number,

      'Supplier Return credit refund - '
      ||
      v_return.return_number,

      nullif(
        trim(
          coalesce(
            p_notes,
            ''
          )
        ),
        ''
      )
    );


  /* =======================================================
   * Resolve GL Accounts
   * ======================================================= */

  v_financial_gl_account_id :=
    public.get_financial_account_gl_account(
      v_financial_account.id
    );


  v_supplier_advance_account_id :=
    public.get_mapped_gl_account(
      'supplier_advances'
    );


  /* =======================================================
   * Build General Ledger Lines
   * ======================================================= */

  v_lines :=
    jsonb_build_array(

      jsonb_build_object(
        'glAccountId',
          v_financial_gl_account_id,

        'debit',
          v_amount,

        'credit',
          0,

        'baseDebit',
          v_base_amount,

        'baseCredit',
          0,

        'description',
          'Supplier Return credit refund received - '
          ||
          v_return.return_number,

        'supplierId',
          v_return.supplier_id,

        'financialAccountId',
          v_financial_account.id,

        'sourceLineType',
          'supplier_return_credit_refund',

        'sourceLineId',
          v_refund_id,

        'sourceLineNumber',
          1
      ),

      jsonb_build_object(
        'glAccountId',
          v_supplier_advance_account_id,

        'debit',
          0,

        'credit',
          v_amount,

        'baseDebit',
          0,

        'baseCredit',
          v_base_amount,

        'description',
          'Supplier Return credit refunded by supplier - '
          ||
          v_return.return_number,

        'supplierId',
          v_return.supplier_id,

        'sourceLineType',
          'supplier_return_credit_refund',

        'sourceLineId',
          v_refund_id,

        'sourceLineNumber',
          2
      )
    );


  /* =======================================================
   * Post General Ledger
   * ======================================================= */

  v_journal_entry_id :=
    public.post_erp_gl_journal(
      'supplier_return_credit_refund',

      v_refund_id,

      v_refund_number,

      coalesce(
        p_refund_date,
        current_date
      ),

      coalesce(
        p_posting_date,
        current_date
      ),

      'Supplier Return Credit Refund - '
      ||
      v_return.return_number,

      upper(
        v_return.currency_code
      ),

      v_return.exchange_rate,

      v_lines
    );


  /* =======================================================
   * Finalize Refund
   * ======================================================= */

  update
    public.supplier_return_credit_refunds

  set
    account_transaction_id =
      v_account_transaction_id,

    journal_entry_id =
      v_journal_entry_id,

    updated_at =
      now()

  where
    id =
      v_refund_id;


  return
    v_refund_id;

end;
$$;


/* =========================================================
 * 9. Permissions
 * ========================================================= */

revoke all
on function
  public.next_supplier_return_credit_refund_number(
    date
  )
from public;


revoke all
on function
  public.refund_supplier_return_credit(
    uuid,
    uuid,
    numeric,
    date,
    date,
    text,
    text
  )
from public;


grant execute
on function
  public.refund_supplier_return_credit(
    uuid,
    uuid,
    numeric,
    date,
    date,
    text,
    text
  )
to authenticated;


/* =========================================================
 * 10. Documentation
 * ========================================================= */

comment on function
  public.next_supplier_return_credit_refund_number(
    date
  )
is
  'Generates Supplier Return credit refund numbers in SPRF-YYYY-NNNNNN format.';


comment on function
  public.refund_supplier_return_credit(
    uuid,
    uuid,
    numeric,
    date,
    date,
    text,
    text
  )
is
  'Atomically receives a Supplier Return credit refund into an operational financial account and posts Dr Financial Account / Cr Supplier Advances through the controlled General Ledger engine.';

/* =========================================================
 * 11. Supplier Return Credit Availability — Refund Aware
 *
 * Extends Migration 127.
 *
 * AVAILABLE CREDIT
 * ----------------
 *
 *   supplier_credit_amount
 *   -
 *   supplier_credit_applied_amount
 *   -
 *   successfully posted Supplier Return refunds
 *
 * Refund consumption is derived from the immutable refund
 * ledger rather than maintained as another mutable running
 * total on supplier_returns.
 * ========================================================= */

create or replace view
  public.available_supplier_return_credits

with (
  security_invoker = true
)

as

select
  supplier_return.id
    as supplier_return_id,

  supplier_return.return_number,

  supplier_return.supplier_id,

  supplier_return.quick_purchase_id,

  supplier_return.posting_date,

  supplier_return.currency_code,

  supplier_return.exchange_rate,

  supplier_return.supplier_credit_amount,

    supplier_return.supplier_credit_applied_amount,

  greatest(
    round(
      supplier_return.supplier_credit_amount
      -
      supplier_return.supplier_credit_applied_amount
      -
      coalesce(
        refund_summary.refunded_amount,
        0
      ),
      2
    ),
    0
  )
    as supplier_credit_available,

  round(
    coalesce(
      refund_summary.refunded_amount,
      0
    ),
    2
  )
    as supplier_credit_refunded_amount

from
  public.supplier_returns
    supplier_return

left join lateral
(
  select
    coalesce(
      sum(
        refund.amount
      ),
      0
    )
      as refunded_amount

  from
    public.supplier_return_credit_refunds
      refund

  where
    refund.supplier_return_id =
      supplier_return.id

    and

    refund.journal_entry_id
      is not null
)
  refund_summary
on
  true

where
  supplier_return.status =
    'posted'

  and

  round(
    supplier_return.supplier_credit_amount
    -
    supplier_return.supplier_credit_applied_amount
    -
    coalesce(
      refund_summary.refunded_amount,
      0
    ),
    2
  )
    >
    0;


/* =========================================================
 * 12. Documentation — Refund-Aware Credit Availability
 * ========================================================= */

comment on view
  public.available_supplier_return_credits
is
  'Available posted Supplier Return credit after deducting credit applied against Quick Purchases and successfully posted supplier cash/bank refunds.';

/* =========================================================
 * 13. Refund-Aware Supplier Credit Application
 * ========================================================= */

create or replace function
  public.apply_supplier_return_credit(
    p_supplier_return_id uuid,
    p_quick_purchase_id uuid,
    p_amount numeric,
    p_application_date date
      default current_date,
    p_posting_date date
      default current_date,
    p_notes text
      default null
  )
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;

  v_return
    public.supplier_returns%rowtype;

  v_purchase
    public.quick_purchases%rowtype;

    v_available_credit numeric(18, 2);

  v_refunded_amount numeric(18, 2);

  v_outstanding_payable numeric(18, 2);

  v_amount numeric(18, 2);

  v_base_amount numeric(18, 2);

  v_accounts_payable_account_id uuid;

  v_supplier_advances_account_id uuid;

  v_application_id uuid;

  v_journal_id uuid;

  v_lines jsonb;

begin

  /* =======================================================
   * Authentication
   * ======================================================= */

  v_user_id :=
    auth.uid();


  if
    v_user_id is null
  then
    raise exception
      'Authentication is required.';
  end if;


  if
    not public.is_admin()
  then
    raise exception
      'Administrator access is required.';
  end if;


  /* =======================================================
   * Validate Input
   * ======================================================= */

  if
    p_supplier_return_id is null
  then
    raise exception
      'Supplier Return ID is required.';
  end if;


  if
    p_quick_purchase_id is null
  then
    raise exception
      'Quick Purchase ID is required.';
  end if;


  if
    p_amount is null
    or
    p_amount <= 0
  then
    raise exception
      'Supplier credit application amount must be greater than zero.';
  end if;


  if
    p_application_date is null
  then
    raise exception
      'Application date is required.';
  end if;


  if
    p_posting_date is null
  then
    raise exception
      'Posting date is required.';
  end if;


  v_amount :=
    round(
      p_amount,
      2
    );


  /* =======================================================
   * Lock Supplier Return
   * ======================================================= */

  select
    *
  into
    v_return
  from
    public.supplier_returns
  where
    id =
      p_supplier_return_id
  for update;


  if not found then
    raise exception
      'Supplier Return was not found.';
  end if;


  if
    v_return.status <>
      'posted'
  then
    raise exception
      'Supplier Return % must be posted before its credit can be applied.',
      v_return.return_number;
  end if;


  if
    coalesce(
      v_return.supplier_credit_amount,
      0
    ) <= 0
  then
    raise exception
      'Supplier Return % does not contain available supplier credit.',
      v_return.return_number;
  end if;


  /* =======================================================
   * Prevent Application to Original Purchase
   * ======================================================= */

  if
    v_return.quick_purchase_id =
      p_quick_purchase_id
  then
    raise exception
      'Supplier Return credit cannot be applied back to its originating Quick Purchase.';
  end if;


    /* =======================================================
   * Calculate Successfully Refunded Supplier Credit
   *
   * The Supplier Return row is already locked above.
   *
   * Only finalized refund records having a posted GL journal
   * consume Supplier Return credit.
   * ======================================================= */

  select
    coalesce(
      sum(
        refund.amount
      ),
      0
    )

  into
    v_refunded_amount

  from
    public.supplier_return_credit_refunds
      refund

  where
    refund.supplier_return_id =
      v_return.id

    and

    refund.journal_entry_id
      is not null;


  /* =======================================================
   * Calculate Available Supplier Credit
   *
   * Available =
   *
   *   original Supplier Return credit
   *   - credit already applied to purchases
   *   - credit already refunded by supplier
   * ======================================================= */

    v_available_credit :=
    greatest(
      round(
        coalesce(
          v_return.supplier_credit_amount,
          0
        )
        -
        coalesce(
          v_return.supplier_credit_applied_amount,
          0
        )
        -
        coalesce(
          v_refunded_amount,
          0
        ),
        2
      ),
      0
    );


  if
    v_available_credit <= 0
  then
    raise exception
      'Supplier Return % has no remaining supplier credit.',
      v_return.return_number;
  end if;


  if
    v_amount >
      v_available_credit
  then
    raise exception
      'Requested amount % exceeds available Supplier Return credit %.',
      v_amount,
      v_available_credit;
  end if;


  /* =======================================================
   * Lock Target Quick Purchase
   * ======================================================= */

  select
    *
  into
    v_purchase
  from
    public.quick_purchases
  where
    id =
      p_quick_purchase_id
  for update;


  if not found then
    raise exception
      'Target Quick Purchase was not found.';
  end if;


  /* =======================================================
   * Supplier Validation
   * ======================================================= */

  if
    v_purchase.supplier_id is null
  then
    raise exception
      'Quick Purchase % does not have a registered supplier.',
      v_purchase.purchase_number;
  end if;


  if
    v_purchase.supplier_id <>
      v_return.supplier_id
  then
    raise exception
      'Supplier Return % and Quick Purchase % belong to different suppliers.',
      v_return.return_number,
      v_purchase.purchase_number;
  end if;


  /* =======================================================
   * Currency Validation
   *
   * Cross-currency Supplier Return applications require a
   * separate FX realization model and are intentionally not
   * permitted here.
   * ======================================================= */

  if
    upper(
      trim(
        v_purchase.currency_code
      )
    )
    <>
    upper(
      trim(
        v_return.currency_code
      )
    )
  then
    raise exception
      'Supplier Return credit currency % does not match Quick Purchase currency %.',
      v_return.currency_code,
      v_purchase.currency_code;
  end if;


  /* =======================================================
   * Refresh Operational Payable
   *
   * Existing Quick Purchase synchronization remains the
   * authority for operational paid/balance fields.
   * ======================================================= */

  perform
    public.sync_quick_purchase_paid_amount(
      v_purchase.id
    );


  /*
   * Reload after synchronization while retaining the row
   * lock in this transaction.
   */

  select
    *
  into
    v_purchase
  from
    public.quick_purchases
  where
    id =
      p_quick_purchase_id
  for update;


  /* =======================================================
   * Calculate Outstanding Payable
   * ======================================================= */

  v_outstanding_payable :=
  round(
    greatest(
      coalesce(
        v_purchase.balance_due,
        0
      ),
      0
    ),
    2
  );

  if
    v_outstanding_payable <= 0
  then
    raise exception
      'Quick Purchase % does not have an outstanding payable.',
      v_purchase.purchase_number;
  end if;


  if
    v_amount >
      v_outstanding_payable
  then
    raise exception
      'Requested amount % exceeds Quick Purchase outstanding payable %.',
      v_amount,
      v_outstanding_payable;
  end if;


  /* =======================================================
   * Resolve GL Accounts
   * ======================================================= */

  v_accounts_payable_account_id :=
    public.get_mapped_gl_account(
      'accounts_payable'
    );


  v_supplier_advances_account_id :=
    public.get_mapped_gl_account(
      'supplier_advances'
    );


  if
    v_accounts_payable_account_id is null
  then
    raise exception
      'Accounts Payable GL account mapping is missing.';
  end if;


  if
    v_supplier_advances_account_id is null
  then
    raise exception
      'Supplier Advances GL account mapping is missing.';
  end if;


  /* =======================================================
   * Base Currency Amount
   * ======================================================= */

  v_base_amount :=
    round(
      v_amount
      *
      v_return.exchange_rate,
      2
    );


  if
    v_base_amount <= 0
  then
    raise exception
      'Supplier credit base amount must be greater than zero.';
  end if;


  /* =======================================================
   * Create Immutable Application Record
   * ======================================================= */

  insert into
    public.supplier_return_credit_applications
    (
      supplier_return_id,
      quick_purchase_id,
      supplier_id,

      application_date,
      posting_date,

      currency_code,
      exchange_rate,

      amount,
      base_amount,

      notes,

      created_by,
      created_at,
      updated_at
    )

  values
    (
      v_return.id,
      v_purchase.id,
      v_return.supplier_id,

      p_application_date,
      p_posting_date,

      upper(
        trim(
          v_return.currency_code
        )
      ),

      v_return.exchange_rate,

      v_amount,
      v_base_amount,

      nullif(
        trim(
          coalesce(
            p_notes,
            ''
          )
        ),
        ''
      ),

      v_user_id,
      now(),
      now()
    )

  returning
    id
  into
    v_application_id;


  /* =======================================================
   * Build GL Lines
   *
   * Dr Accounts Payable
   * Cr Supplier Advances
   * ======================================================= */

  v_lines :=
    jsonb_build_array(

      jsonb_build_object(
        'glAccountId',
          v_accounts_payable_account_id,

        'debit',
          v_amount,

        'credit',
          0,

        'baseDebit',
          v_base_amount,

        'baseCredit',
          0,

        'description',
          'Supplier credit applied to '
          ||
          v_purchase.purchase_number,

        'supplierId',
          v_return.supplier_id
      ),

      jsonb_build_object(
        'glAccountId',
          v_supplier_advances_account_id,

        'debit',
          0,

        'credit',
          v_amount,

        'baseDebit',
          0,

        'baseCredit',
          v_base_amount,

        'description',
          'Supplier Return credit applied from '
          ||
          v_return.return_number,

        'supplierId',
          v_return.supplier_id
      )

    );


  /* =======================================================
   * Post Through Controlled GL Engine
   * ======================================================= */

  v_journal_id :=
    public.post_erp_gl_journal(
      'supplier_return_credit_application',

      v_application_id,

      v_return.return_number
      ||
      ' -> '
      ||
      v_purchase.purchase_number,

      p_application_date,

      p_posting_date,

      'Supplier Return credit application - '
      ||
      v_return.return_number
      ||
      ' against '
      ||
      v_purchase.purchase_number,

      upper(
        trim(
          v_return.currency_code
        )
      ),

      v_return.exchange_rate,

      v_lines
    );


  /* =======================================================
   * Finalize Application
   * ======================================================= */

  update
    public.supplier_return_credit_applications

  set
    journal_entry_id =
      v_journal_id,

    updated_at =
      now()

  where
    id =
      v_application_id;


  /* =======================================================
   * Consume Supplier Return Credit
   * ======================================================= */

  update
    public.supplier_returns

  set
    supplier_credit_applied_amount =
      round(
        coalesce(
          supplier_credit_applied_amount,
          0
        )
        +
        v_amount,
        2
      ),

    updated_by =
      v_user_id,

    updated_at =
      now()

  where
    id =
      v_return.id;


  /* =======================================================
   * Synchronize Target Quick Purchase
   * ======================================================= */

  perform
    public.sync_quick_purchase_paid_amount(
      v_purchase.id
    );


  return
    v_application_id;

end;
$$;



